In [66]:
# create torch class 
import torch
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out =self.sigmoid(out)
        return out 
        
        

In [67]:
# creating datasets
features=torch.rand(10,5)

In [68]:
# create model
model=Model(features.shape[1])

In [69]:
# call model forward pass
#model.forward(features)
model(features)

tensor([[0.3418],
        [0.4410],
        [0.3616],
        [0.3463],
        [0.4542],
        [0.3689],
        [0.4458],
        [0.4520],
        [0.3780],
        [0.3301]], grad_fn=<SigmoidBackward0>)

In [43]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.2753, -0.1628, -0.0096,  0.1810, -0.2728]], requires_grad=True)

In [44]:
model.linear.bias

Parameter containing:
tensor([0.2389], requires_grad=True)

In [45]:
! pip install torchinfo

In [46]:
from torchinfo import summary 
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## creating a neural network with hidden layer

In [70]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out =self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out 
        

In [71]:
# creating datasets
features=torch.rand(10,5)

In [72]:
# create model
model2=Model(features.shape[1])

In [73]:
# call model forward pass
#model.forward(features)
model2(features)

tensor([[0.5660],
        [0.5622],
        [0.5687],
        [0.5479],
        [0.5726],
        [0.5438],
        [0.5665],
        [0.5481],
        [0.5628],
        [0.5372]], grad_fn=<SigmoidBackward0>)

In [74]:
# show model weights
model2.linear1.weight

Parameter containing:
tensor([[ 0.0331,  0.0237,  0.1808, -0.0969,  0.0815],
        [ 0.3865,  0.3634,  0.3839,  0.2658, -0.0449],
        [-0.3801,  0.0365,  0.1501, -0.0172,  0.4117]], requires_grad=True)

In [75]:
model2.linear2.weight

Parameter containing:
tensor([[ 0.4056,  0.2121, -0.3023]], requires_grad=True)

In [76]:
model2.linear2.bias

Parameter containing:
tensor([0.1627], requires_grad=True)

In [77]:
model2.linear1.bias

Parameter containing:
tensor([-0.1873, -0.3894, -0.3289], requires_grad=True)

In [87]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## making sequential container for the forward to simplify  it


In [82]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out=self.network(features)
       
        return out 
        

In [83]:
# creating datasets
features=torch.rand(10,5)

In [84]:
# create model
model3=Model(features.shape[1])

In [85]:
# call model forward pass
#model.forward(features)
model3(features)

tensor([[0.4150],
        [0.3973],
        [0.3973],
        [0.3973],
        [0.3984],
        [0.3973],
        [0.3973],
        [0.3973],
        [0.3973],
        [0.3971]], grad_fn=<SigmoidBackward0>)

In [88]:
summary(model3,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00